language: java
jdk: openjdk8

before_install:
  - ./gradlew assemble

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - ./gradlew test jacocoTestCoverageVerification
  -  COVERAGE=0.5 ./gradlew test jacocoTestCoverageVerification
