language: java
jdk: openjdk8

env:
  - COVERAGE=0.35


before_install:
  - ./gradlew assemble

script:
  - ./gradlew test jacocoTestCoverageVerification
  - echo 'WIP'
  - $COVERAGE ./gradlew test jacocoTestCoverageVerification 
