language: java
jdk: openjdk8
env:
  - COVERAGE=0.5
  - COVERAGE=0.4

before_install:
  - ./gradlew assemble

script:
- if ["$(COVERAGE)" = 0.5]; then
     ./gradlew test jacocoTestCoverageVerification
  fi;
