sudo: required
services:
  - docker
script:
- /.gradlew -p ./monolithic/ui packageToContainer
- docker tag zutherb/monolithic-shop:latest <borhencherif>/<borhen_image>
- docker push $DOCKER_LOGIN/monolithic-shop:latest
deploy:
  - provider: script
    script:
      #!/usr/bin/env bash
      set -e
      ./script/docker tag zutherb/monolithic-shop:latest <borhencherif>/<borhen_image>
      ./script/docker push $DOCKER_LOGIN/monolithic-shop:latest
      ./script/deploy.sh;
      ./script/chmod +x ./script/deploy.sh 
