language: java
jdk: openjdk8
env:
    - COVERAGE=0.31
stages:
  - Java8
  - Java9
before_install:
   - ./gradlew assemble
jobs:
 include:
    - stage: Java8
      name: "Java8-test"
      script:
      - ./gradlew -p ./monolithic/ui check;
      - ./gradlew -p ./monolithic/service/cart check;
      - ./gradlew -p ./monolithic/service/user check;
      - ./gradlew -p ./monolithic/repository/cart check;
      - ./gradlew -p ./monolithic/repository/product check;

      env:
      - jdk=openjdk8
    - stage: Java9
      name: "Java9-test"
      script:
      - ./gradlew -p ./monolithic/ui check;
      - ./gradlew -p ./monolithic/service/cart check;
      - ./gradlew -p ./monolithic/service/user check;
      - ./gradlew -p ./monolithic/repository/cart check;
      - ./gradlew -p ./monolithic/repository/product check;
      env:
      - jdk=openjdk9
